import { Geist, Geist_Mono, Hind_Siliguri, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

export const inter = Inter({
  weight: ["100", "200", "400", "500", "600", "800"],
});

export const hindSiliguri = Hind_Siliguri({
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased`}>
        <header className=" md:w-11/12 mx-auto">
          <Navbar />
        </header>
        <main className="py-3 md:w-11/12 mx-auto min-h-[calc(100vh-360px)]">
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
